[phases.setup]
nixPkgs = ["python310", "pip"]
cmds = ["pip install gunicorn"]  # Install Gunicorn here

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmds = ["gunicorn blog_project.wsgi:application --bind 0.0.0.0:$PORT"]

